<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://soa" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="http://soa" xmlns:intf="http://soa" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<!--WSDL created by Apache Axis version: 1.4
Built on Apr 22, 2006 (06:55:48 PDT)-->

   <wsdl:message name="searchRequest">

      <wsdl:part name="in0" type="xsd:string">

      </wsdl:part>

   </wsdl:message>

   <wsdl:message name="searchResponse">

      <wsdl:part name="searchReturn" type="xsd:string">

      </wsdl:part>

   </wsdl:message>

   <wsdl:portType name="Searchable">

      <wsdl:operation name="search" parameterOrder="in0">

         <wsdl:input message="impl:searchRequest" name="searchRequest">

       </wsdl:input>

         <wsdl:output message="impl:searchResponse" name="searchResponse">

       </wsdl:output>

      </wsdl:operation>

   </wsdl:portType>

   <wsdl:binding name="SearchableSoapBinding" type="impl:Searchable">

      <wsdlsoap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>

      <wsdl:operation name="search">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="searchRequest">

            <wsdlsoap:body namespace="http://soa" use="literal"/>

         </wsdl:input>

         <wsdl:output name="searchResponse">

            <wsdlsoap:body namespace="http://soa" use="literal"/>

         </wsdl:output>

      </wsdl:operation>

   </wsdl:binding>

   <wsdl:service name="SearchableService">

      <wsdl:port binding="impl:SearchableSoapBinding" name="Searchable">

         <wsdlsoap:address location="http://localhost:8080//services/soa/Searchable"/>

      </wsdl:port>

   </wsdl:service>

</wsdl:definitions>
